"""Replace plants_per_tray with number_of_trays

Revision ID: 229ca633f69e
Revises: f596cb15d949
Create Date: 2026-07-28 21:26:48.931058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '229ca633f69e'
down_revision = 'f596cb15d949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_trays', sa.Integer(), nullable=False))
        batch_op.drop_column('plants_per_tray')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_batches', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plants_per_tray', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('number_of_trays')

    # ### end Alembic commands ###
