"""Add snapshot fields to booking item

Revision ID: 317bbac06d02
Revises: c7fe6b2e955f
Create Date: 2026-07-29 18:10:34.381694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317bbac06d02'
down_revision = 'c7fe6b2e955f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('plant_name', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('variety_name', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_items', schema=None) as batch_op:
        batch_op.drop_column('variety_name')
        batch_op.drop_column('plant_name')

    # ### end Alembic commands ###
