"""Add inventory fields

Revision ID: 3e0443732ba7
Revises: e399984238a6
Create Date: 2026-07-29 18:48:08.805673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e0443732ba7'
down_revision = 'e399984238a6'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('plant_batches', schema=None) as batch_op:

        batch_op.add_column(
            sa.Column(
                'reserved_plants',
                sa.Integer(),
                nullable=False,
                server_default='0'
            )
        )

        batch_op.add_column(
            sa.Column(
                'sold_plants',
                sa.Integer(),
                nullable=False,
                server_default='0'
            )
        )

        batch_op.add_column(
            sa.Column(
                'damaged_plants',
                sa.Integer(),
                nullable=False,
                server_default='0'
            )
        )

        batch_op.add_column(
            sa.Column(
                'imported_plants',
                sa.Integer(),
                nullable=False,
                server_default='0'
            )
        )

        batch_op.add_column(
            sa.Column(
                'exported_plants',
                sa.Integer(),
                nullable=False,
                server_default='0'
            )
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_batches', schema=None) as batch_op:
        batch_op.drop_column('exported_plants')
        batch_op.drop_column('imported_plants')
        batch_op.drop_column('damaged_plants')
        batch_op.drop_column('sold_plants')
        batch_op.drop_column('reserved_plants')

    # ### end Alembic commands ###
