"""Booking pricing

Revision ID: c772f31105f5
Revises: 3e0443732ba7
Create Date: 2026-07-29 19:05:11.051951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c772f31105f5'
down_revision = '3e0443732ba7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('selling_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.drop_column('rate')
        batch_op.drop_column('amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rate', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_column('total_amount')
        batch_op.drop_column('selling_price')
        batch_op.drop_column('batch_price')

    # ### end Alembic commands ###
