"""Add selling price to batches

Revision ID: e399984238a6
Revises: 317bbac06d02
Create Date: 2026-07-29 18:28:45.186973

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e399984238a6'
down_revision = '317bbac06d02'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_batches', schema=None) as batch_op:
       batch_op.add_column(
    sa.Column(
        'selling_price',
        sa.Numeric(10,2),
        nullable=False,
        server_default='0'
    )
)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plant_batches', schema=None) as batch_op:
        batch_op.drop_column('selling_price')

    # ### end Alembic commands ###
