"""Add line number to booking items

Revision ID: ef0b67804648
Revises: c772f31105f5
Create Date: 2026-07-29 19:19:24.451799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef0b67804648'
down_revision = 'c772f31105f5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_per_plant', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('line_no', sa.Integer(), nullable=False))
        batch_op.drop_column('selling_price')
        batch_op.drop_column('batch_price')
        batch_op.drop_column('variety_name')
        batch_op.drop_column('plant_name')
        batch_op.drop_column('total_amount')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('plant_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('variety_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('batch_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('selling_price', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.drop_column('line_no')
        batch_op.drop_column('total_price')
        batch_op.drop_column('price_per_plant')

    # ### end Alembic commands ###
