"""Update PlantBatch to use Variety

Revision ID: f596cb15d949
Revises: fdd754619602
Create Date: 2026-07-28 21:18:47.280882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f596cb15d949'
down_revision = 'fdd754619602'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plant_batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('plant_id', sa.Integer(), nullable=False),
    sa.Column('variety_id', sa.Integer(), nullable=False),
    sa.Column('tray_size_id', sa.Integer(), nullable=False),
    sa.Column('plants_per_tray', sa.Integer(), nullable=False),
    sa.Column('estimated_plants', sa.Integer(), nullable=False),
    sa.Column('sowing_date', sa.Date(), nullable=False),
    sa.Column('ready_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['plant_id'], ['plants.id'], ),
    sa.ForeignKeyConstraint(['tray_size_id'], ['tray_sizes.id'], ),
    sa.ForeignKeyConstraint(['variety_id'], ['varieties.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plant_batches')
    # ### end Alembic commands ###
